# Linear Regression

Linear regression analysis is used to predict the value of a variable based on the value of another variable. The variable you want to predict is called the dependent variable. The variable you are using to predict the other variable's value is called the independent variable

This week, your task involves conducting multi-class linear regression on batsmen salaries. You'll use the average runs scored per game and the strike rate as independent variables. The goal is to predict the salary as the dependent variable. Additionally, you'll be categorizing the data based on the years.

The dataset is Data_Mendeley.csv given on GitHub. Feel free to create any new functions required.

In [ ]:
#import important libraries
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

preparing data

In [ ]:
#mounting gdrive
from google.colab import files


uploaded = files.upload()

Saving Data_Mendeley.csv to Data_Mendeley.csv


In [ ]:
import pandas as pd
df = pd.read_csv('Data_Mendeley.csv')
unique_years=df['Year'].unique()

yearlist={}
for x in unique_years:
  yearlist[x]=(df[df['Year']==x])
x1={}
x2={}
y={}
for a in unique_years:
  x1[a]=yearlist[a]["Ave"].to_list()
  x2[a]=yearlist[a]["StrRate"].to_list()
  y[a]=yearlist[a]["Final Price"].to_list()

Forward pass

In [ ]:
def forward(x,w,b):
    y_pred = np.dot(x, w) + b
    return y_pred
# for i in unique_years:
#   x=[x1[i][0],x2[i][0]]
#   print(x)
#   alpha=[]
#   alpha=np.concatenate((alpha,x))
# print(alpha)




[19.0, 96.93]
[51.66, 130.98]
[15.85, 93.27]
[34.66, 128.39]
[39.87, 161.11]
[36.0, 164.38]
[35.9, 158.63]
[46.63, 175.08]
[52.84, 168.79]
[27.0, 132.51]
[ 27.   132.51]


Mean Squared Loss

In [ ]:
def loss(y,y_pred): #Mean Squared Loss
   mse = np.mean((y - y_pred)**2)
   return mse

Implement Linear regression here :)

In [ ]:
def train(x, y, learning_rate, epochs):
    num_samples, num_features = x.shape
    w = np.zeros(num_features)
    b = 0
    print(num_samples)

    for epoch in range(epochs):
        y_pred = forward(x,w,b)
        dw = (1 / num_samples) *np.dot(x.T, ( y_pred-y))
        db =  (1 / num_samples)*np.sum( y_pred-y)
        w =w- learning_rate * dw
        b =b- learning_rate * db
    print(w,b)
    return w, b

learning_rate=0.0000001
epochs=100

for year in unique_years:
    print(year)
    x = np.column_stack((x1[year], x2[year]))
    y_values = np.array(y[year])
    w, b = train(x, y_values,learning_rate,epochs)
    predictions = forward(x, w, b)
    print(predictions)

2008
47
[ 3587.89913779 16643.55721532] 136.93635822434243
[1.68156702e+06 2.57690912e+06 3.98769200e+05 1.36936358e+02
 2.58438236e+06 1.51050669e+06 3.94867499e+05 8.39490595e+05
 3.62589918e+06 1.36936358e+02 6.73055023e+05 2.08181402e+05
 2.34218902e+06 2.34782639e+06 2.31731773e+06 2.49240273e+06
 2.99104397e+06 8.32314797e+05 1.95801769e+06 1.70395955e+06
 1.36936358e+02 2.37125659e+06 5.60248547e+05 2.12976154e+06
 3.09763808e+06 1.36936358e+02 1.79094167e+06 2.61967288e+06
 8.35902696e+05 1.94234713e+06 2.08199194e+06 2.25061624e+06
 2.03653633e+06 2.59479819e+06 2.21044206e+06 2.69531202e+06
 2.57046483e+06 2.05382186e+06 2.57303667e+06 2.50449254e+06
 1.92123154e+06 1.80302685e+06 3.19291761e+06 2.33797781e+06
 3.09097614e+06 2.78723666e+06 1.34647371e+06]
2009
56
[ 3189.26055817 16453.55941533] 147.10537527914605
[2.31999152e+06 2.15763329e+06 2.00290756e+06 2.35745640e+06
 2.16672883e+06 2.07611483e+06 1.47105375e+02 1.64550305e+06
 1.10013064e+06 2.03781447e+06 2.05855767e

# Logistic Regression

Logistic regression is a process of modeling the probability of a discrete outcome given an input variable. The most common logistic regression models a binary outcome; something that can take two values such as true/false, yes/no, and so on.

In this week you will be doing logistic regression on breast cancer dataset using sklearn library. Feel free to create any new functions required.

In [ ]:
#importinf libraries

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Prepare Data

In [ ]:
breast_cancer = datasets.load_breast_cancer()
X, y = breast_cancer.data, breast_cancer.target
print(X,y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
#spliting data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[-0.36180827 -0.26521011 -0.31715702 ... -0.07967528 -0.52798733
   0.2506337 ]
 [-0.8632675   0.71560604 -0.85646012 ... -0.76980239  0.44312729
  -0.20987332]
 [-0.4334453   0.32513895 -0.41286667 ... -0.06601541 -1.1169427
   0.0329492 ]
 ...
 [-0.479293   -0.17689018 -0.45697634 ... -0.20261414  0.18670009
   0.17414996]
 [ 1.16835876 -0.15364809  1.17466524 ...  0.26789258  0.19828067
  -0.23394164]
 [-0.40765597 -1.29715887 -0.42826344 ... -0.78042674 -0.88036793
  -0.80355834]]


Forward pass

In [ ]:
def forward_log(x,w,b):
  a=np.dot(x,w)+b
  return 1/(1+np.exp(-a))


Binary cross entropy loss

In [ ]:
def BCELoss(y,y_pred):
  # print(len(y))
  return (-1/len(y))*np.sum(y*np.log(y_pred)+(1-y)*np.log(1-y_pred))

Implement Logistic Regression here :)

In [ ]:
def train(x, y, learning_rate, epochs):
    num_samples, num_features = x.shape
    w = np.zeros(num_features)
    b = 0
    for epoch in range(epochs):
        y_pred = forward_log(x,w,b)

        dw = (1 / num_samples) *np.dot(x.T, ( y_pred-y))
        db =  (1 / num_samples)*np.sum( y_pred-y)
        w =w- learning_rate * dw
        b =b- learning_rate * db
    yk=forward_log(x,w,b)
    return yk


learning_rate=0.0000001
epochs=100

y_trained=train(X_train, y_train, learning_rate, epochs)
# print(y_trained)
y_predicted=[0 if y<=0.5 else 1 for y in y_trained]
print(y_predicted)
print(BCELoss(y_train,y_trained))



[1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 